{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "ebbfabd6-6f21-485a-ac05-d8ca014f490d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model training complete.\n",
      "\n",
      "Validation Set Performance:\n",
      "\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       1.00      0.92      0.96        13\n",
      "           1       0.93      1.00      0.96        13\n",
      "\n",
      "    accuracy                           0.96        26\n",
      "   macro avg       0.96      0.96      0.96        26\n",
      "weighted avg       0.96      0.96      0.96        26\n",
      "\n",
      "Final Test Set Performance:\n",
      "\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       0.88      1.00      0.93         7\n",
      "           1       1.00      0.90      0.95        10\n",
      "\n",
      "    accuracy                           0.94        17\n",
      "   macro avg       0.94      0.95      0.94        17\n",
      "weighted avg       0.95      0.94      0.94        17\n",
      "\n",
      "\n",
      " Enter your email content:\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      " You win\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Extracted Features: [Suspicious Keywords: 1, Links: 0, Caps: 0]\n",
      "\n",
      "Predicted Spam Probability: 0.0163\n",
      "\n",
      "FINAL VERDICT:\n",
      "⚠ This email is NOT spam, but it looks unusual for this sender (CLT anomaly).\n",
      " Please review it manually before trusting it.\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import re\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import classification_report\n",
    "\n",
    "# --- Step 1: Load Data ---\n",
    "df = pd.read_excel(\"email_dataset.xlsx\")\n",
    "\n",
    "# Features and labels\n",
    "X = df[['suspicious_keywords', 'links', 'capitalized_words']].values\n",
    "y = df['label'].values  # 0 = Ham, 1 = Spam\n",
    "\n",
    "# --- Step 2: Split Dataset (Train 75%, Validation 15%, Test 10%) ---\n",
    "\n",
    "X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.1, random_state=42)\n",
    "\n",
    "\n",
    "X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.1667, random_state=42)\n",
    "\n",
    "# --- Step 3: Train Model ---\n",
    "model = LogisticRegression(class_weight='balanced')\n",
    "model.fit(X_train, y_train)\n",
    "print(\"Model training complete.\\n\")\n",
    "\n",
    "# --- Step 4: Evaluate on Validation Set ---\n",
    "print(\"Validation Set Performance:\\n\")\n",
    "val_preds = model.predict(X_val)\n",
    "print(classification_report(y_val, val_preds))\n",
    "\n",
    "# --- Step 5: Evaluate on Test Set ---\n",
    "print(\"Final Test Set Performance:\\n\")\n",
    "test_preds = model.predict(X_test)\n",
    "print(classification_report(y_test, test_preds))\n",
    "\n",
    "# --- Step 6: Feature Extraction from Text ---\n",
    "def extract_features(email_text):\n",
    "    suspicious_keywords = ['free', 'win', 'click', 'now', 'offer', 'money', 'cash', 'limited', 'prize', 'urgent', 'claim', 'exclusive', 'today']\n",
    "\n",
    "    num_keywords = sum(len(re.findall(rf'\\b{kw}\\b', email_text, re.IGNORECASE)) for kw in suspicious_keywords)\n",
    "\n",
    "    num_links = len(re.findall(r'(http[s]?://\\S+|www\\.\\S+|\\S+\\.com)', email_text))\n",
    "    num_caps = sum(1 for word in email_text.split() if word.isupper() and len(word) > 1)\n",
    "    return np.array([num_keywords, num_links, num_caps])\n",
    "\n",
    "# Step 7: Sender history for CLT anomaly check\n",
    "emails_from_sender = np.array([\n",
    "    [1, 0, 1],\n",
    "    [2, 0, 0],\n",
    "    [1, 1, 1],\n",
    "    [0, 0, 0],\n",
    "    [2, 0, 1],\n",
    "    [1, 0, 1],\n",
    "    [0, 1, 0],\n",
    "    [1, 0, 1]\n",
    "])\n",
    "\n",
    "mean_features = np.mean(emails_from_sender, axis=0)\n",
    "std_features = np.std(emails_from_sender, axis=0, ddof=1)\n",
    "n = len(emails_from_sender)\n",
    "std_error = std_features / np.sqrt(n)\n",
    "z = 1.96  # 95% confidence interval\n",
    "\n",
    "conf_lower = mean_features - z * std_error\n",
    "conf_upper = mean_features + z * std_error\n",
    "\n",
    "# --- Step 8: Input Email and Predict ---\n",
    "print(\"\\n Enter your email content:\")\n",
    "email_input = input()\n",
    "\n",
    "new_email = extract_features(email_input)\n",
    "print(f\"\\nExtracted Features: [Suspicious Keywords: {new_email[0]}, Links: {new_email[1]}, Caps: {new_email[2]}]\")\n",
    "\n",
    "# --- Step 9: Anomaly Check ---\n",
    "is_anomaly = np.any(new_email < conf_lower) | np.any(new_email > conf_upper)\n",
    "\n",
    "# --- Step 10: ML Prediction ---\n",
    "prediction = model.predict(new_email.reshape(1, -1))[0]\n",
    "\n",
    "# Get probability\n",
    "proba = model.predict_proba(new_email.reshape(1, -1))[0][1]  # Probability of being spam\n",
    "print(f\"\\nPredicted Spam Probability: {proba:.4f}\")\n",
    "\n",
    "# --- Step 11: Final Decision Message ---\n",
    "print(\"\\nFINAL VERDICT:\")\n",
    "\n",
    "\n",
    "if prediction == 1:\n",
    "    print(\"❌This email is SPAM.\")\n",
    "    print(\" Reason: Content looks like spam (ML model prediction).\")\n",
    "\n",
    "    if is_anomaly:\n",
    "        print(\"⚠ Also looks unusual for this sender (CLT anomaly).\")\n",
    "elif is_anomaly:\n",
    "    print(\"⚠ This email is NOT spam, but it looks unusual for this sender (CLT anomaly).\")\n",
    "    print(\" Please review it manually before trusting it.\")\n",
    "else:\n",
    "    print(\"✅ This email is NOT SPAM. It appears safe.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d4b86ec0-a6f5-4102-bf20-73560d024f5b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
