# -*- coding: utf-8 -*-
"""Spam_Email_Classifyer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MW6ofYXX4wjmsgcz73afYX8TKrxpHFT0
"""

import numpy as np
import pandas as pd
import re
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# --- Step 1: Load Data ---
df = pd.read_excel("email_dataset.xlsx")

# Features and labels
X = df[['suspicious_keywords', 'links', 'capitalized_words']].values
y = df['label'].values  # 0 = Ham, 1 = Spam

# --- Step 2: Split Dataset (Train 75%, Validation 15%, Test 10%) ---

X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.1, random_state=42)


X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.1667, random_state=42)

# --- Step 3: Train Model ---
model = LogisticRegression(class_weight='balanced')
model.fit(X_train, y_train)
print("Model training complete.\n")

# --- Step 4: Evaluate on Validation Set ---
print("Validation Set Performance:\n")
val_preds = model.predict(X_val)
print(classification_report(y_val, val_preds))

# --- Step 5: Evaluate on Test Set ---
print("Final Test Set Performance:\n")
test_preds = model.predict(X_test)
print(classification_report(y_test, test_preds))

# --- Step 6: Feature Extraction from Text ---
def extract_features(email_text):
    suspicious_keywords = ['free', 'win', 'click', 'now', 'offer', 'money', 'cash', 'limited', 'prize', 'urgent', 'claim', 'exclusive', 'today']

    num_keywords = sum(len(re.findall(rf'\b{kw}\b', email_text, re.IGNORECASE)) for kw in suspicious_keywords)

    num_links = len(re.findall(r'(http[s]?://\S+|www\.\S+|\S+\.com)', email_text))
    num_caps = sum(1 for word in email_text.split() if word.isupper() and len(word) > 1)
    return np.array([num_keywords, num_links, num_caps])

# Step 7: Sender history for CLT anomaly check
emails_from_sender = np.array([
    [1, 0, 1],
    [2, 0, 0],
    [1, 1, 1],
    [0, 0, 0],
    [2, 0, 1],
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1]
])

mean_features = np.mean(emails_from_sender, axis=0)
std_features = np.std(emails_from_sender, axis=0, ddof=1)
n = len(emails_from_sender)
std_error = std_features / np.sqrt(n)
z = 1.96  # 95% confidence interval

conf_lower = mean_features - z * std_error
conf_upper = mean_features + z * std_error

# --- Step 8: Input Email and Predict ---
print("\n Enter your email content:")
email_input = input()

new_email = extract_features(email_input)
print(f"\nExtracted Features: [Suspicious Keywords: {new_email[0]}, Links: {new_email[1]}, Caps: {new_email[2]}]")

# --- Step 9: Anomaly Check ---
is_anomaly = np.any(new_email < conf_lower) | np.any(new_email > conf_upper)

# --- Step 10: ML Prediction ---
prediction = model.predict(new_email.reshape(1, -1))[0]

# Get probability
proba = model.predict_proba(new_email.reshape(1, -1))[0][1]  # Probability of being spam
print(f"\nPredicted Spam Probability: {proba:.4f}")

# --- Step 11: Final Decision Message ---
print("\nFINAL VERDICT:")


if prediction == 1:
    print("❌This email is SPAM.")
    print(" Reason: Content looks like spam (ML model prediction).")

    if is_anomaly:
        print("⚠ Also looks unusual for this sender (CLT anomaly).")
elif is_anomaly:
    print("⚠ This email is NOT spam, but it looks unusual for this sender (CLT anomaly).")
    print(" Please review it manually before trusting it.")
else:
    print("✅ This email is NOT SPAM. It appears safe.")

from google.colab import files
uploaded = files.upload()